# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-19 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u6c7d\u8f66\u54c1\u724c')),
                ('logo', models.ImageField(upload_to='brand', verbose_name='logo')),
                ('key', models.CharField(max_length=2, verbose_name='\u4e2d\u6587\u62fc\u97f3\u5927\u5199\u9996\u5b57\u6bcd')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u54c1\u724c',
                'verbose_name_plural': '\u54c1\u724c',
            },
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=20, verbose_name='\u8f66\u7cfb')),
                ('version', models.CharField(max_length=20, verbose_name='\u578b\u53f7')),
                ('kuanhao', models.CharField(max_length=6, verbose_name='\u6b3e\u53f7')),
                ('licence_date', models.DateTimeField(verbose_name='\u4e0a\u724c\u65f6\u95f4')),
                ('annual_expire', models.DateTimeField(verbose_name='\u5e74\u68c0\u5230\u671f\u65f6\u95f4')),
                ('insurance_expire', models.DateTimeField(verbose_name='\u5f3a\u9669\u5230\u671f\u65f6\u95f4')),
                ('serial_number', models.IntegerField(verbose_name='\u8f66\u8f86\u7f16\u53f7')),
                ('color', models.CharField(max_length=10, verbose_name='\u8f66\u8eab\u989c\u8272')),
                ('car_body', models.CharField(choices=[('SUV', 'SUV'), ('CRV', 'CRV'), ('RAV', 'RAV'), ('SRV', 'SRV'), ('MPV', 'MPV')], max_length=6, verbose_name='\u8f66\u4f53\u5f62\u5f0f')),
                ('gear_box', models.CharField(choices=[('AT', 'AT\u81ea\u52a8'), ('MT', 'MT\u624b\u52a8'), ('CVT', 'CVT\u65e0\u7ea7')], max_length=12, verbose_name='\u53d8\u901f\u7bb1')),
                ('displacement', models.CharField(max_length=10, verbose_name='\u6392\u91cf')),
                ('emission_standard', models.CharField(choices=[('yi', '\u56fd\u4e00'), ('er', '\u56fd\u4e8c'), ('san', '\u56fd\u4e09'), ('si', '\u56fd\u56db'), ('wu', '\u56fd\u4e94'), ('liu', '\u56fd\u516d')], max_length=6, verbose_name='\u53d8\u901f\u7bb1')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Brand', verbose_name='\u54c1\u724c')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('samll', '\u5c0f\u578b'), ('jiaoc', '\u8f7f\u8f66'), ('paoc', '\u8dd1\u8f66'), ('SUV', 'SUV'), ('MVP', 'SUV'), ('fangc', '\u623f\u8f66')], max_length=6, verbose_name='\u8f66\u578b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8f66\u578b',
                'verbose_name_plural': '\u8f66\u578b',
            },
        ),
        migrations.AddField(
            model_name='cardetail',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Type', verbose_name='\u8f66\u578b'),
        ),
    ]
