# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-19 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/%Y/%m', verbose_name='\u8f66\u8f86\u56fe\u7247')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6c7d\u8f66\u56fe\u7247',
                'verbose_name_plural': '\u6c7d\u8f66\u56fe\u7247',
            },
        ),
        migrations.AlterModelOptions(
            name='cardetail',
            options={'verbose_name': '\u6c7d\u8f66\u8be6\u60c5', 'verbose_name_plural': '\u6c7d\u8f66\u8be6\u60c5'},
        ),
        migrations.AddField(
            model_name='cardetail',
            name='anti_lock_braking_system',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u9632\u62b1\u6b7b\u5236\u52a8\u7cfb\u7edf'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='assitant_seat_adjust',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u526f\u9a7e\u9a76\u5ea7\u6905\u7535\u52a8\u8c03\u8282'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='auto_head_light',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u81ea\u52a8\u5934\u706f'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='back_eye_camera',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u5012\u8f66\u5f71\u50cf\u7cfb\u7edf'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='back_radar',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u540e\u5012\u8f66\u96f7\u8fbe'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='back_seat_heating',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u540e\u6392\u5ea7\u6905\u52a0\u70ed'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='back_seat_memory',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u540e\u6392\u5ea7\u6905\u8bb0\u5fc6'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='back_seat_wind',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u540e\u6392\u5ea7\u6905\u901a\u98ce'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='commercial_insurance_expire',
            field=models.CharField(default='\u5df2\u5230\u671f\u6216\u6682\u65e0', max_length=20, verbose_name='\u5546\u4e1a\u9669\u5230\u671f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='contact',
            field=models.CharField(default='\u9500\u552e\u70ed\u7ebf (15737112660)', max_length=20, verbose_name='\u8054\u7cfb\u4eba'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='cruise_control',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u5b9a\u901f\u5de1\u822a'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='desc',
            field=models.TextField(default='', verbose_name='\u8be6\u7ec6\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='downpayment_percent',
            field=models.IntegerField(default='30', verbose_name='\u9996\u4ed8\u6bd4\u4f8b(%)'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='drive_type',
            field=models.CharField(choices=[('two', '4\xd72(\u4e24\u8f6e\u9a71\u52a8)'), ('four', '4\xd74(\u56db\u8f6e\u9a71\u52a8)'), ('six', '6\xd76(\u516d\u8f6e\u9a71\u52a8)'), ('other', '\u4e0d\u9650')], default='other', max_length=20, verbose_name='\u9a71\u52a8\u5f62\u5f0f'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='driver_seat_adjust',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u9a7e\u9a76\u5458\u5ea7\u6905\u7535\u52a8\u8c03\u8282'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='forward_radar',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u524d\u9a7b\u8f66\u96f7\u8fbe'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='front_seat_heating',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u524d\u6392\u5ea7\u6905\u52a0\u70ed'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='front_seat_memory',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u524d\u6392\u5ea7\u6905\u8bb0\u5fc6'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='front_seat_wind',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u524d\u6392\u5ea7\u6905\u901a\u98ce'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='fuel',
            field=models.CharField(choices=[('qy', '\u6c7d\u6cb9'), ('cy', '\u67f4\u6cb9'), ('yd', '\u6cb9\u7535\u6df7\u5408'), ('dd', '\u7535\u52a8')], default='qy', max_length=20, verbose_name='\u71c3\u6599\u5f62\u5f0f'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='gps',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u5bfc\u822a\u7cfb\u7edf'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='hid',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u6c19\u6c14\u5927\u706f'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='inner_color',
            field=models.CharField(default='', max_length=20, verbose_name='\u5185\u9970\u989c\u8272'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='installment',
            field=models.CharField(choices=[('1', '\u662f'), ('0', '\u5426')], default='1', max_length=2, verbose_name='\u652f\u6301\u5206\u671f'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='istop',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u53d1\u52a8\u673a\u542f\u505c'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='key_nums',
            field=models.IntegerField(default=0, verbose_name='\u94a5\u5319\uff08\u628a\uff09'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='keyless_entry',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u65e0\u94a5\u5319\u8fdb\u5165'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='keyless_go',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u65e0\u94a5\u5319\u542f\u52a8'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='leather_seats',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u771f\u76ae\u5ea7\u6905'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='licence',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u884c\u9a76\u8bc1'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='light_clean',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u5927\u706f\u6e05\u6d17'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='new_car_invoice',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u65b0\u8f66\u53d1\u7968'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='new_car_price',
            field=models.IntegerField(default=0, verbose_name='\u65b0\u8f66\u4ef7(\u4e07)'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='new_car_warranty',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u65b0\u8f66\u8d28\u4fdd'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='power_mirror',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u7535\u52a8\u6298\u53e0\u540e\u89c6\u955c'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='price',
            field=models.IntegerField(default=0, verbose_name='\u9500\u552e\u4ef7(\u4e07)'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='price_type',
            field=models.CharField(choices=[('1', '\u4e00\u53e3\u4ef7'), ('0', '\u9762\u8bae')], default='1', max_length=6, verbose_name='\u4ef7\u683c\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='produce_address',
            field=models.CharField(default='', max_length=20, verbose_name='\u4ea7\u5730'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u51fa\u5382\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='rearview_mirror_heating',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u540e\u89c6\u955c\u52a0\u70ed'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='registration',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u767b\u8bb0\u8bc1'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='screen',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u4e2d\u63a7\u53f0\u6db2\u6676\u5c4f'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='seat_nums',
            field=models.IntegerField(default=0, verbose_name='\u5ea7\u4f4d\u6570'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='status',
            field=models.CharField(choices=[('zs', '\u5728\u552e'), ('ys', '\u5df2\u552e'), ('zt', '\u5728\u9014'), ('yd', '\u5df2\u8ba2')], default='zs', max_length=4, verbose_name='\u8f66\u6e90\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='sunroof',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u5168\u666f\u5929\u7a97'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='tax',
            field=models.CharField(default='\u5df2\u5f81\u6536', max_length=20, verbose_name='\u662f\u5426\u5f81\u6536\u8d2d\u7f6e\u7a0e'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='transfer_fee',
            field=models.CharField(choices=[('1', '\u662f'), ('0', '\u5426')], default='1', max_length=2, verbose_name='\u8fc7\u6237\u8d39'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='transfer_invoice',
            field=models.CharField(choices=[('1', '\u6709'), ('0', '\u65e0'), ('2', '')], default='1', max_length=2, verbose_name='\u8fc7\u6237\u7968'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='transfer_nums',
            field=models.IntegerField(default=0, verbose_name='\u8fc7\u6237\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='travel_distance',
            field=models.CharField(default='0\u516c\u91cc', max_length=20, verbose_name='\u884c\u9a76\u91cc\u7a0b(\u516c\u91cc)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='brand/%Y/%m', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='annual_expire',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5e74\u68c0\u5230\u671f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='displacement',
            field=models.CharField(default='0L', max_length=10, verbose_name='\u6392\u91cf(L))'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='emission_standard',
            field=models.CharField(choices=[('one', '\u56fd\u4e00'), ('two', '\u56fd\u4e8c'), ('three', '\u56fd\u4e09'), ('four', '\u56fd\u56db'), ('five', '\u56fd\u4e94'), ('six', '\u56fd\u516d')], default='zs', max_length=6, verbose_name='\u53d8\u901f\u7bb1'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='gear_box',
            field=models.CharField(choices=[('AT', 'AT\u81ea\u52a8'), ('MT', 'MT\u624b\u52a8'), ('CVT', 'CVT\u65e0\u7ea7')], default='AT', max_length=12, verbose_name='\u53d8\u901f\u7bb1'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='insurance_expire',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f3a\u9669\u5230\u671f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='licence_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u724c\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarDetail', verbose_name='\u8f66\u540d'),
        ),
    ]
