# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20180822_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='CarType',
        ),
        migrations.RemoveField(
            model_name='cardetail',
            name='type',
        ),
        migrations.AddField(
            model_name='cardetail',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.CarType', verbose_name='\u8f66\u578b'),
        ),
    ]
