# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20180823_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='\u9996\u9875\u663e\u793a'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/brand/', verbose_name='logo'),
        ),
    ]
