# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20180823_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='car_type',
            field=models.CharField(choices=[('samll', '\u5c0f\u578b'), ('jiaoc', '\u8f7f\u8f66'), ('paoc', '\u8dd1\u8f66'), ('SUV', 'SUV'), ('MVP', 'SUV'), ('fangc', '\u623f\u8f66')], default='small', max_length=10, verbose_name='\u8f66\u578b'),
        ),
    ]
