# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-23 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20180823_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarType',
        ),
    ]
