# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_delete_cartype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='emission_standard',
            field=models.CharField(choices=[('one', '\u56fd\u4e00'), ('two', '\u56fd\u4e8c'), ('three', '\u56fd\u4e09'), ('four', '\u56fd\u56db'), ('five', '\u56fd\u4e94'), ('six', '\u56fd\u516d')], default='zs', max_length=6, verbose_name='\u6392\u653e\u6807\u51c6'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='new_car_price',
            field=models.CharField(default=0, max_length=20, verbose_name='\u65b0\u8f66\u4ef7(\u4e07)'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='price',
            field=models.CharField(default=0, max_length=20, verbose_name='\u9500\u552e\u4ef7(\u4e07)'),
        ),
    ]
