# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-23 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20180823_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/images', verbose_name='\u8f66\u8f86\u56fe\u7247')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarDetail', verbose_name='\u8f66\u540d')),
            ],
            options={
                'verbose_name': '\u6c7d\u8f66\u5c01\u9762\u56fe',
                'verbose_name_plural': '\u6c7d\u8f66\u5c01\u9762\u56fe',
            },
        ),
    ]
