# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_carhomeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='car_age',
            field=models.CharField(default=0, max_length=5, verbose_name='\u8f66\u9f84(\u5e74)'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='displacement',
            field=models.CharField(default='', max_length=10, verbose_name='\u6392\u91cf(L))'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='travel_distance',
            field=models.CharField(default='0', max_length=20, verbose_name='\u884c\u9a76\u91cc\u7a0b(\u4e07\u516c\u91cc)'),
        ),
    ]
