# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20180825_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='is_roll',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u6eda\u52a8\u64ad\u653e'),
        ),
    ]
