# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-25 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_cardetail_is_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6b21\u6570'),
        ),
    ]
