# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-29 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20180826_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(default='', max_length=30, verbose_name='\u8f66\u7cfb')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('car_name', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='cars.Brand', verbose_name='\u6c7d\u8f66\u54c1\u724c')),
            ],
            options={
                'verbose_name': '\u8f66\u7cfb',
                'verbose_name_plural': '\u8f66\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=6, verbose_name='\u8f66\u578b')),
                ('image', models.ImageField(upload_to='cars/type', verbose_name='\u8f66\u578b\u56fe\u7247')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8f66\u578b',
                'verbose_name_plural': '\u8f66\u578b',
            },
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='car_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u578b'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7cfb'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='car_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.CarSeries', verbose_name='\u8f66\u7cfb'),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='car_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.CarType', verbose_name='\u8f66\u578b'),
        ),
    ]
