# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-30 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_cardetail_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetail',
            name='desc',
        ),
    ]
