# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-30 10:47
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_remove_cardetail_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u6c7d\u8f66\u8be6\u7ec6\u63cf\u8ff0'),
        ),
    ]
