# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_cardetail_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='cars/images', verbose_name='\u6c7d\u8f66\u5c01\u9762\u56fe'),
        ),
    ]
