# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_auto_20180902_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='key',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2, verbose_name='\u4e2d\u6587\u62fc\u97f3\u5927\u5199\u9996\u5b57\u6bcd'),
        ),
    ]
