# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_activitycar_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='car_body',
            field=models.CharField(choices=[('SUV', 'SUV'), ('CRV', 'CRV'), ('RAV', 'RAV'), ('SRV', 'SRV'), ('MPV', 'MPV')], default='SUV', max_length=6, verbose_name='\u8f66\u4f53\u5f62\u5f0f'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Brand', verbose_name='\u54c1\u724c'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='serial_number',
            field=models.IntegerField(default=0, verbose_name='\u8f66\u8f86\u7f16\u53f7'),
        ),
    ]
