# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-06 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_auto_20181004_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carhomeimage',
            name='name',
        ),
        migrations.DeleteModel(
            name='CarHomeImage',
        ),
    ]
