# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-22 18:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_auto_20180822_1700'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30, verbose_name='\u6c7d\u8f66\u54c1\u724c')),
                ('series', models.CharField(max_length=20, verbose_name='\u8f66\u7cfb')),
                ('use_years', models.CharField(max_length=20, verbose_name='\u4f7f\u7528\u5e74\u9650')),
                ('purchase_data', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8ba1\u5212\u8d2d\u4e70\u65f6\u95f4')),
                ('mix_price', models.IntegerField(default=0, verbose_name='\u6700\u4f4e\u4ef7')),
                ('max_price', models.IntegerField(default=0, verbose_name='\u6700\u9ad8\u4ef7')),
                ('desc', models.TextField(default='', verbose_name='\u5176\u4ed6\u8981\u6c42')),
            ],
            options={
                'verbose_name': '\u79c1\u4eba\u5b9a\u5236',
                'verbose_name_plural': '\u79c1\u4eba\u5b9a\u5236',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.IntegerField(default=0, verbose_name='\u8f66\u8f86\u7684id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('wf', '\u672a\u4ed8\u5b9a\u91d1'), ('yg', '\u5df2\u8d2d')], default='wf', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarDetail', verbose_name='\u6c7d\u8f66')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8ba2\u5355',
                'verbose_name_plural': '\u7528\u6237\u8ba2\u5355',
            },
        ),
    ]
