# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-01 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0002_personalneeds_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalneeds',
            old_name='purchase_data',
            new_name='purchase_date',
        ),
        migrations.AddField(
            model_name='personalneeds',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
