# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-01 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20180901_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalneeds',
            old_name='mix_price',
            new_name='min_price',
        ),
    ]
