# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20180901_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalneeds',
            name='purchase_date',
            field=models.CharField(default='', max_length=20, verbose_name='\u8ba1\u5212\u8d2d\u4e70\u65f6\u95f4'),
        ),
    ]
