# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-02 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20180901_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='cars',
        ),
    ]
