# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-03 15:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0009_auto_20180902_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(default=0, verbose_name='\u6c7d\u8f66id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6d4f\u89c8\u8bb0\u5f55',
                'verbose_name_plural': '\u6d4f\u89c8\u8bb0\u5f55',
            },
        ),
    ]
