# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0011_usersell'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersell',
            name='car_type',
            field=models.CharField(default='', max_length=5, verbose_name='\u8f66\u578b'),
        ),
        migrations.AlterField(
            model_name='usersell',
            name='licence_date',
            field=models.CharField(default='', max_length=20, verbose_name='\u4e0a\u724c\u65f6\u95f4'),
        ),
    ]
