# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-22 20:15
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='\u90d1\u5dde\u5e02\u7ba1\u57ce\u533a\u7d2b\u8346\u5c71\u4e1c\u5927\u8857\u88d5\u9e3f\u82b1\u56ed', max_length=100, verbose_name='\u5730\u5740')),
                ('tel', models.CharField(default='400-886-8888', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('email', models.EmailField(default='dpy0705@126.com', max_length=254, verbose_name='\u90ae\u7bb1')),
                ('site', models.URLField(default='http://www.hnyijin.com', verbose_name='\u7f51\u5740')),
                ('weibo', models.CharField(default='@\u4ebf\u91d1\u4e8c\u624b\u540d\u8f66\u5e7f\u573a', max_length=100, verbose_name='\u5fae\u535a')),
                ('wechat', models.CharField(default='hnyijin', max_length=100, verbose_name='\u5fae\u4fe1')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8054\u7cfb\u6211\u4eec',
                'verbose_name_plural': '\u8054\u7cfb\u6211\u4eec',
            },
        ),
        migrations.CreateModel(
            name='CorporationDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_brief', DjangoUeditor.models.UEditorField(default='', verbose_name='\u516c\u53f8\u7b80\u4ecb')),
                ('strength', DjangoUeditor.models.UEditorField(default='', verbose_name='\u516c\u53f8\u4f18\u52bf')),
                ('honor', DjangoUeditor.models.UEditorField(default='', verbose_name='\u516c\u53f8\u8363\u8a89')),
                ('service', DjangoUeditor.models.UEditorField(default='', verbose_name='\u552e\u540e\u670d\u52a1')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='CorporationNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='\u65b0\u95fb\u5185\u5bb9')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u516c\u53f8\u52a8\u6001',
                'verbose_name_plural': '\u516c\u53f8\u52a8\u6001',
            },
        ),
    ]
