# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-22 20:32
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0002_auto_20180822_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpHonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honor', DjangoUeditor.models.UEditorField(default='', verbose_name='\u516c\u53f8\u8363\u8a89')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u516c\u53f8\u8363\u8a89',
                'verbose_name_plural': '\u516c\u53f8\u8363\u8a89',
            },
        ),
        migrations.CreateModel(
            name='CorpService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', DjangoUeditor.models.UEditorField(default='', verbose_name='\u552e\u540e\u670d\u52a1')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u552e\u540e\u670d\u52a1',
                'verbose_name_plural': '\u552e\u540e\u670d\u52a1',
            },
        ),
        migrations.CreateModel(
            name='CorpStrength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', DjangoUeditor.models.UEditorField(default='', verbose_name='\u516c\u53f8\u4f18\u52bf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u516c\u53f8\u4f18\u52bf',
                'verbose_name_plural': '\u516c\u53f8\u4f18\u52bf',
            },
        ),
        migrations.AlterModelOptions(
            name='corporationdesc',
            options={'verbose_name': '\u516c\u53f8\u7b80\u4ecb', 'verbose_name_plural': '\u516c\u53f8\u7b80\u4ecb'},
        ),
        migrations.RemoveField(
            model_name='corporationdesc',
            name='honor',
        ),
        migrations.RemoveField(
            model_name='corporationdesc',
            name='service',
        ),
        migrations.RemoveField(
            model_name='corporationdesc',
            name='strength',
        ),
    ]
