# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0003_auto_20180822_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='corp/news_image', verbose_name='\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='corporationnews',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u9996\u9875\u5c55\u793a'),
        ),
        migrations.AlterField(
            model_name='corporationnews',
            name='title',
            field=models.CharField(default='', max_length=40, verbose_name='\u6807\u9898'),
        ),
    ]
