# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-08 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0004_auto_20180908_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationnews',
            name='is_show_image',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u9996\u9875\u5c55\u793a\u56fe\u7247'),
        ),
    ]
