# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0005_corporationnews_is_show_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationnews',
            name='title',
            field=models.CharField(default='', max_length=36, verbose_name='\u6807\u9898'),
        ),
    ]
